// autopilot.js — function-driven self-play that keeps running in the background.
//
// The performance is generated by natural functions only (catalog A2–A8): event
// timing is a Poisson / exponential process, and parameters drift on the global
// natural-function LFOs (golden / Lorenz / Kuramoto-r / 1f / gauss / Bessel).
//
// Background survival: requestAnimationFrame is paused when a tab is hidden, so
// the simulation and the note scheduling live on a setInterval control loop
// instead. Events are scheduled AHEAD on the AudioContext clock (lookahead), so
// even when a background tab throttles the timer to ~1 s the audio stays filled
// and the auto-play never stops or clumps. Visuals may pause in the background —
// only the sound must continue.

import { GlobalLFOs } from './modmatrix.js';

export class AutoPilot {
  constructor(ctx, { rate = 1.4, lookahead = 1.5 } = {}) {
    this.ctx = ctx;
    this.enabled = false;
    this.rate = rate;               // mean events per second (Poisson)
    this.lookahead = lookahead;     // seconds of events to schedule ahead
    this.lfo = new GlobalLFOs();
    this.nextEvent = 0;
  }
  setRate(r) { this.rate = Math.max(0.05, r); }
  _interval() { return -Math.log(Math.random() + 1e-9) / this.rate; } // exponential

  // Advance by real elapsed dt (sub-stepped so a large background gap stays
  // numerically stable) and return { v: LFO values, events: [audioTime, …] }.
  update(dt) {
    let rem = Math.min(Math.max(dt, 0), 2);
    while (rem > 0) { const h = Math.min(rem, 0.02); this.lfo.update(h, this.enabled); rem -= h; }
    const events = [];
    if (this.enabled) {
      const now = this.ctx.currentTime, horizon = now + this.lookahead;
      if (this.nextEvent < now) this.nextEvent = now;
      while (this.nextEvent < horizon) { events.push(this.nextEvent); this.nextEvent += this._interval(); }
    } else {
      this.nextEvent = this.ctx.currentTime; // reset so re-enabling starts clean
    }
    return { v: this.lfo.values, events };
  }
}

// A setInterval control loop that measures real dt (works in the background).
// fn(dt) is called ~every `ms`; returns a stop() handle.
export function controlLoop(fn, ms = 30) {
  let last = performance.now();
  const id = setInterval(() => {
    const now = performance.now();
    const dt = (now - last) / 1000; last = now;
    fn(dt);
  }, ms);
  return () => clearInterval(id);
}
